#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace GameFramework.Core.UI.Editor
{
    internal static class UIBindingCodeGenerator
    {
        public const string OutputPathPrefsKey = "SGFCore.UIBinding.OutputPath";
        public const string DefaultOutputPath = "Assets/Scripts/UIBindings";

        public static string OutputPath
        {
            get => EditorPrefs.GetString(OutputPathPrefsKey, DefaultOutputPath);
            set => EditorPrefs.SetString(OutputPathPrefsKey, string.IsNullOrWhiteSpace(value) ? DefaultOutputPath : value);
        }

        public static string GetGeneratedScriptPath(UIFormBase form)
        {
            if (form == null)
            {
                return string.Empty;
            }

            return NormalizePath(Path.Combine(OutputPath, form.GetType().Name + ".Binding.cs"));
        }

        public static void Generate(UIFormBase form)
        {
            if (form == null)
            {
                return;
            }

            UIBindingField[] fields = form.GetBindingFields();
            string scriptPath = GetGeneratedScriptPath(form);

            if (fields == null || fields.Length == 0)
            {
                DeleteGeneratedFile(scriptPath);
                AssetDatabase.Refresh();
                return;
            }

            MonoScript monoScript = MonoScript.FromMonoBehaviour(form);
            Type formType = form.GetType();
            if (!IsPartialClass(monoScript, formType.Name))
            {
                bool shouldContinue = EditorUtility.DisplayDialog(
                    "UI Binding",
                    $"{formType.Name} 当前脚本没有声明 partial。生成绑定代码前建议把类改成 partial class，否则会编译失败。\n\n是否仍然生成？",
                    "继续生成",
                    "取消");

                if (!shouldContinue)
                {
                    return;
                }
            }

            string directory = Path.GetDirectoryName(scriptPath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            string code = BuildCode(formType, fields);
            File.WriteAllText(scriptPath, code, new UTF8Encoding(false));
            AssetDatabase.Refresh();
        }

        private static string BuildCode(Type formType, UIBindingField[] fields)
        {
            HashSet<string> namespaces = new HashSet<string> { "UnityEngine" };
            List<string> fieldLines = new List<string>();

            for (int i = 0; i < fields.Length; i++)
            {
                UIBindingField field = fields[i];
                if (field == null)
                {
                    continue;
                }

                if (field.Access == UIBindingAccess.Header)
                {
                    if (!string.IsNullOrWhiteSpace(field.VarName))
                    {
                        fieldLines.Add($"[Header(\"{Escape(field.VarName)}\")]");
                    }
                    continue;
                }

                Type componentType = UIBindingEditorUtility.ResolveType(field.ComponentTypeName);
                if (componentType == null || string.IsNullOrWhiteSpace(field.VarName))
                {
                    continue;
                }

                if (!string.IsNullOrEmpty(componentType.Namespace))
                {
                    namespaces.Add(componentType.Namespace);
                }

                string access = GetAccessKeyword(field.Access);
                string typeName = UIBindingEditorUtility.GetTypeCodeName(componentType);
                bool isArray = field.Targets != null && field.Targets.Length > 1;
                string arraySuffix = isArray ? "[]" : string.Empty;
                fieldLines.Add($"[SerializeField] {access} {typeName}{arraySuffix} {field.VarName};");
            }

            StringBuilder builder = new StringBuilder();
            builder.AppendLine("//------------------------------------------------------------------------------");
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("//     This file is generated by SGFCore UI Binding Editor. Do not edit manually.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("//------------------------------------------------------------------------------");

            List<string> orderedNamespaces = new List<string>(namespaces);
            orderedNamespaces.Sort(StringComparer.Ordinal);
            for (int i = 0; i < orderedNamespaces.Count; i++)
            {
                builder.AppendLine($"using {orderedNamespaces[i]};");
            }

            builder.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(formType.Namespace);
            if (hasNamespace)
            {
                builder.AppendLine($"namespace {formType.Namespace}");
                builder.AppendLine("{");
            }

            string indent = hasNamespace ? "    " : string.Empty;
            builder.AppendLine($"{indent}public partial class {formType.Name}");
            builder.AppendLine($"{indent}{{");
            builder.AppendLine($"{indent}    [Space(10)]");
            builder.AppendLine($"{indent}    [Header(\"UI Binding\")]");

            for (int i = 0; i < fieldLines.Count; i++)
            {
                builder.AppendLine($"{indent}    {fieldLines[i]}");
            }

            builder.AppendLine($"{indent}}}");
            if (hasNamespace)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        private static string GetAccessKeyword(UIBindingAccess access)
        {
            switch (access)
            {
                case UIBindingAccess.Protected:
                    return "protected";
                case UIBindingAccess.Public:
                    return "public";
                default:
                    return "private";
            }
        }

        private static bool IsPartialClass(MonoScript monoScript, string className)
        {
            if (monoScript == null)
            {
                return false;
            }

            string scriptPath = AssetDatabase.GetAssetPath(monoScript);
            if (string.IsNullOrEmpty(scriptPath) || !File.Exists(scriptPath))
            {
                return false;
            }

            string text = File.ReadAllText(scriptPath);
            return text.Contains("partial class " + className);
        }

        private static void DeleteGeneratedFile(string scriptPath)
        {
            if (File.Exists(scriptPath))
            {
                File.Delete(scriptPath);
            }

            string metaPath = scriptPath + ".meta";
            if (File.Exists(metaPath))
            {
                File.Delete(metaPath);
            }
        }

        private static string Escape(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string NormalizePath(string path)
        {
            return path.Replace('\\', '/');
        }
    }
}
#endif
